[ADD] l10n_ru_doc module
OCA/l10n-russia pull request #7
Opened 2023-12-23 11:40 UTC by Katulos

2023-12-23 11:46 UTC, Katulos commented
Hi, @pedrobaeza!
Could you please accept a PR?

2023-12-23 12:18 UTC, pedrobaeza commented
I can't give my opinion on the content of the PR, being something specific of the localization. You should ask other PSC or contributors of this repo.

Formally speaking about the contribution itself, there are changes that shouldn't be done on l10n_ru nor the main readme.

2023-12-24 05:40 UTC, em230418 commented on l10n_ru_doc/demo/l10n_ru_doc_demo.xml
> +        <field name="city">г.Москва</field>
Предлагаю не менять название компании и прочие поля в демке.

2023-12-24 06:14 UTC, em230418 requested changes

2023-12-24 06:14 UTC, em230418 commented on l10n_ru_doc/demo/l10n_ru_doc_demo.xml
> +    </record>
Аналогично https://github.com/OCA/l10n-russia/pull/7/files#r1435767597

2023-12-24 06:14 UTC, em230418 commented on l10n_ru_doc/demo/l10n_ru_doc_demo.xml
> +    </record>
Аналогично https://github.com/OCA/l10n-russia/pull/7/files#r1435767597

2023-12-24 06:14 UTC, em230418 commented on l10n_ru_doc/__manifest__.py
> +    "version": "11.0.0.0.1",
11.0.1.0.0

2023-12-24 06:14 UTC, em230418 commented on l10n_ru_doc/__manifest__.py
> +    "depends": ["sale_management"],
Можно ли просто "sale" использовать или надо обязательно sale_management?

2023-12-24 06:14 UTC, em230418 commented on l10n_ru_doc/views/account_invoice_view.xml
> +                </button>
Допустим есть 2 юрлица и для каждого настроена своя компания. Одно юрлицо - российское, другое - из стран персидского залива, допустим саудиты. Согласно этому изменению, от саудитского юрлица будут отправляться документы в российском формате, когда как в реальности надо отправлять в "саудитском" формате.

В более новых версиях Odoo это реализовали примерно так https://github.com/odoo/odoo/blob/15.0/addons/l10n_gcc_invoice/models/account_move.py
В 11.0 аналогичный метод простой смены шаблона я не встречал.

2023-12-24 06:14 UTC, em230418 commented on l10n_ru_doc/views/res_company_view.xml
> +                    </page>
Тут все поля должны ототбражаться, только если res.company.country_id = РФ.

2023-12-24 06:14 UTC, em230418 commented on l10n_ru_doc/demo/l10n_ru_doc_demo.xml
> +        <field name="okpo">00000000</field>
Аналогично https://github.com/OCA/l10n-russia/pull/7/files#r1435767597

2023-12-24 11:30 UTC, yelizariev commented on README.md
> +[l10n_ru_doc](l10n_ru_doc/) | 11.0.0.0.1 | Russia - Documents
```
<!-- /!\ do not modify below this line -->
```

2024-06-09 12:15 UTC, closed without merging